In [1]:
import numpy as np

In [2]:
##list lst is converted into an array
lst=[1,2,3,4,5]
arr=np.array(lst)

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [6]:
## multinested array
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[9,7,6,8,9]

arr=np.array([lst1,lst2,lst3])

In [7]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [8]:
##(no. of rows, no. of columns)
arr.shape

(3, 5)

In [9]:
##no. of elements should be equal
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [10]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [11]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [12]:
##accessing the array element ....same as list
lsta=[1,2,3,4,5,6,7,8,9]
type(lsta)


list

In [13]:
arr=np.array(lsta)

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
##element at 5th position
arr[5]

6

In [16]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[9,7,6,8,9]

arr=np.array([lst1,lst2,lst3])

In [17]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [19]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [20]:
##element selection is similar to that of list.   syntax is [row range, column range]
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [21]:
arr[0:2,2:4]

array([[3, 4],
       [4, 5]])

In [22]:
arr[1:,1:3]

array([[3, 4],
       [7, 6]])

In [23]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[0:,1:3]

array([[2, 3],
       [3, 4],
       [7, 6]])

In [26]:
arr[0:,2:]

array([[3, 4, 5],
       [4, 5, 6],
       [6, 8, 9]])

In [27]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [28]:
arr[1:,0:3]

array([[2, 3, 4],
       [9, 7, 6]])

In [29]:
arr[0:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [30]:
arr[0:,3:].shape

(3, 2)

In [31]:
arr[1:,0:3].shape

(2, 3)

In [34]:
#excluding last digit
arr=np.arange(5,15,2)

In [35]:
arr

array([ 5,  7,  9, 11, 13])

In [36]:
arr=np.linspace(5,15,40)

In [37]:
arr

array([ 5.        ,  5.25641026,  5.51282051,  5.76923077,  6.02564103,
        6.28205128,  6.53846154,  6.79487179,  7.05128205,  7.30769231,
        7.56410256,  7.82051282,  8.07692308,  8.33333333,  8.58974359,
        8.84615385,  9.1025641 ,  9.35897436,  9.61538462,  9.87179487,
       10.12820513, 10.38461538, 10.64102564, 10.8974359 , 11.15384615,
       11.41025641, 11.66666667, 11.92307692, 12.17948718, 12.43589744,
       12.69230769, 12.94871795, 13.20512821, 13.46153846, 13.71794872,
       13.97435897, 14.23076923, 14.48717949, 14.74358974, 15.        ])

In [38]:
arr.shape

(40,)

In [39]:
arr

array([ 5.        ,  5.25641026,  5.51282051,  5.76923077,  6.02564103,
        6.28205128,  6.53846154,  6.79487179,  7.05128205,  7.30769231,
        7.56410256,  7.82051282,  8.07692308,  8.33333333,  8.58974359,
        8.84615385,  9.1025641 ,  9.35897436,  9.61538462,  9.87179487,
       10.12820513, 10.38461538, 10.64102564, 10.8974359 , 11.15384615,
       11.41025641, 11.66666667, 11.92307692, 12.17948718, 12.43589744,
       12.69230769, 12.94871795, 13.20512821, 13.46153846, 13.71794872,
       13.97435897, 14.23076923, 14.48717949, 14.74358974, 15.        ])

In [42]:
arr=np.array(1,2,3,4,5)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [41]:
lst1=[1,2,3,4,5,6]

In [43]:
arr=np.array(lst1)

In [44]:
arr

array([1, 2, 3, 4, 5, 6])

In [50]:
arr[3]

500

In [51]:
#copy 500 form position 3 onwards
arr[3:]=500

In [52]:
arr

array([  1,   2,   3, 500, 500, 500])

In [53]:
print(arr)

[  1   2   3 500 500 500]


In [61]:
# elements of both arr and arr1 are updated
arr1=arr

In [62]:
arr[1:]=624

In [63]:
arr

array([  1, 624, 624, 624, 624, 624])

In [64]:
arr1

array([  1, 624, 624, 624, 624, 624])

In [65]:
arr1.shape

(6,)

In [66]:
arr1

array([  1, 624, 624, 624, 624, 624])

In [67]:
arr

array([  1, 624, 624, 624, 624, 624])

In [73]:
#elements do not get updated 
arr1=arr.copy()

In [74]:
print(arr)

[  1 624 624 624 624 624]


In [75]:
arr1[2:]=528

In [76]:
print(arr1)

[  1 624 528 528 528 528]


In [77]:
print(arr)
print(arr1)

[  1 624 624 624 624 624]
[  1 624 528 528 528 528]
